// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  iips: [
    {
      type: 'category',
      label: 'Idena Improvement Proposals',
      link: {
        type: 'doc',
        id: 'iip/iips',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'iip',
        },
      ],
    },
  ],

  developer: [
    {
      type: 'category',
      label: 'Idena app',
      link: {
        type: 'generated-index',
        title: 'Idena app',
        //slug: 'developer/send-dna',
        description:
          'Learn how to use official Idena app in your web3 application',
        keywords: ['guides'],
      },

      items: [
        'developer/desktop/sign-in',
        'developer/sign',
        'developer/send-dna',
        'developer/send-invite',
        'developer/send-raw',
        'developer/desktop/dna-url',
      ],
    },

    {
      type: 'category',
      label: 'Idena node',
      link: {
        type: 'generated-index',
        title: 'Idena node',
        description: 'Learn how to run and manage your node',
        keywords: ['guides'],
      },
      items: [
        'developer/node/general',
        'developer/node/node-rpc',
        'developer/node/shared',
      ],
    },

    {
      type: 'category',
      label: 'Smart contracts',
      link: {
        type: 'doc',
        id: 'developer/node/smart-contracts',
      },

      items: [
        'developer/node/quick-start',
        'developer/node/idena-sdk-as',
        'developer/node/smart-contracts-methods',
        {
          type: 'category',
          label: 'Predefined contracts',
          link: {
            type: 'generated-index',
            title: 'Predefined contracts',
            description:
              'Learn about predefined contracts built-in into the Idena node',
            //slug: '/category/guides',
            keywords: ['guides'],
            image: '/img/docusaurus.png',
          },

          items: [
            'developer/node/oracle-lock',
            'developer/node/refundable-oracle-lock',
            'developer/node/multisig',
            'developer/node/time-lock',
          ],
        },
      ],
    },

    {
      type: 'category',
      label: 'Architecture',
      link: {
        type: 'generated-index',
        title: 'Idena architecture',
        description: 'Learn more about Idena architecture',
        keywords: ['guides'],
      },
      items: [
        'developer/validation',
        'developer/ipfs/upload',
        'developer/identity-bridge',
      ],
    },
  ],

  wp: [
    {
      type: 'category',
      label: 'Whitepaper',
      link: {
        type: 'doc',
        id: 'wp/summary',
      },
      items: [
        'wp/manifesto',
        'wp/technology',
        'wp/flip-challenge',
        'wp/economics',
        'wp/roadmap',
      ],
    },
  ],

  community: [
    {
      type: 'category',
      label: 'Community',
      link: {
        type: 'doc',
        id: 'community/resources',
      },
      items: ['community/channels', 'community/affiliate'],
    },
  ],
};

module.exports = sidebars;
